services:
  webserver:
    build:
      context: "./docker/services/php"
    container_name: "zephyrus_webserver"
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
    volumes:
      - ./:/var/www/html
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./docker/services/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  database:
    build:
      context: "./docker/services/postgres"
    container_name: 'zephyrus_database'
    restart: 'always'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'zephyrus'
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev'
